#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import re
from pathlib import Path
from typing import Any


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Render a source-shaped MoonVeil reconstruction from observed VM effects."
    )
    parser.add_argument(
        "--ir",
        type=Path,
        default=Path("outputs/moonveil_v2_devirtualized_ir.json"),
        help="Observed-effect MoonVeil IR generated by devirtualize_moonveil_vm.py.",
    )
    parser.add_argument(
        "--out",
        type=Path,
        default=Path("outputs/moonveil_v2_ssa_reconstruction.lua"),
        help="Source-shaped Luau reconstruction output.",
    )
    parser.add_argument(
        "--trace-diff",
        action="append",
        type=Path,
        default=[Path("work/mv-brutecall/moonveil_dispatch_diff.json")],
        help="Observed dispatch diff JSON to render as chronological trace replay. Repeatable.",
    )
    parser.add_argument(
        "--trace-out",
        type=Path,
        default=Path("outputs/moonveil_v2_trace_replay.lua"),
        help="Lua artifact containing chronological observed VM register writes.",
    )
    parser.add_argument(
        "--max-trace-events",
        type=int,
        default=400,
        help="Maximum chronological diff events to include in the trace replay artifact.",
    )
    return parser.parse_args()


def load_json(path: Path) -> Any:
    return json.loads(path.read_text(encoding="utf-8", errors="replace"))


def write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def lua_quote(value: Any) -> str:
    text = str(value)
    out = ['"']
    for ch in text:
        code = ord(ch)
        if ch == "\\":
            out.append("\\\\")
        elif ch == '"':
            out.append('\\"')
        elif ch == "\n":
            out.append("\\n")
        elif ch == "\r":
            out.append("\\r")
        elif ch == "\t":
            out.append("\\t")
        elif 32 <= code < 127:
            out.append(ch)
        elif code <= 255:
            out.append(f"\\x{code:02X}")
        else:
            out.append("?")
    out.append('"')
    return "".join(out)


def ascii_comment(value: Any) -> str:
    text = str(value)
    out = []
    for ch in text:
        code = ord(ch)
        if ch in "\r\n\t":
            out.append(" ")
        elif 32 <= code < 127:
            out.append(ch)
        elif code <= 255:
            out.append(f"\\x{code:02X}")
        else:
            out.append("?")
    return "".join(out)


def short_ascii(value: Any, limit: int = 180) -> str:
    text = ascii_comment(value)
    if len(text) <= limit:
        return text
    return text[: limit - 3] + "..."


def lua_value_or_nil(value: Any) -> str:
    if value is None:
        return "nil"
    return lua_quote(short_ascii(value))


def value_to_expression(value: str, pc: int, register: str) -> tuple[str, str]:
    if value == "nil":
        return "nil", value
    if value == "bit32":
        return "env.bit32 or bit32", value
    if value == "debug":
        return "env.debug or debug", value
    if value == "userdata:game":
        return "env.game", value
    if value == "userdata:Enum":
        return "env.Enum", value
    if value == "userdata:Enum.Material":
        return "env.Enum and env.Enum.Material or nil", value
    if value == "userdata:Enum.Font":
        return "env.Enum and env.Enum.Font or nil", value
    if value == "function":
        return "function(...) return nil end", value
    if value.startswith("boolean:"):
        return value.split(":", 1)[1], value
    if value.startswith("number:"):
        return value.split(":", 1)[1], value
    if "JuFreutJk" in value:
        return lua_quote("JuFreutJk"), value
    if value.startswith("string[16]"):
        if pc == 6 and register == "r2":
            return "hex_to_bin(MoonVeilSSA.constants.state_chunks_hex[1])", ascii_comment(value)
        if pc in {13, 170} and register in {"r2", "r9"}:
            return "hex_to_bin(MoonVeilSSA.constants.state_chunks_hex[2])", ascii_comment(value)
        if pc in {239, 303}:
            return "hex_to_bin(MoonVeilSSA.constants.final_payload_hex)", ascii_comment(value)
        return "MoonVeilSSA.unknown_string(" + lua_quote(ascii_comment(value)) + ")", ascii_comment(value)
    if value.startswith("string[32]"):
        return "hex_to_bin(MoonVeilSSA.constants.state_chunks_hex[1] .. MoonVeilSSA.constants.state_chunks_hex[2])", ascii_comment(value)
    if value.startswith("string[48]"):
        return "MoonVeilSSA.expected_state()", ascii_comment(value)
    return "MoonVeilSSA.unknown_value(" + lua_quote(ascii_comment(value)) + ")", ascii_comment(value)


def iter_observed_instructions(ir: dict[str, Any]) -> list[dict[str, Any]]:
    rows = []
    for program in ir.get("programs", []):
        program_id = str(program.get("program_id") or "unknown")
        coverage = program.get("coverage") or {}
        program_len = coverage.get("program_size") or program.get("program_len")
        for block in program.get("blocks", []):
            for ins in block.get("instructions", []):
                effect = ins.get("observed_effect")
                if effect and effect.get("writes"):
                    row = dict(ins)
                    row["program_id"] = program_id
                    row["program_len"] = program_len
                    rows.append(row)
    rows.sort(
        key=lambda item: (
            str(item.get("program_id") or ""),
            int(item.get("pc") or 0),
            int(item.get("opcode") or 0),
        )
    )
    return rows


def rows_by_program(rows: list[dict[str, Any]]) -> dict[str, list[dict[str, Any]]]:
    grouped: dict[str, list[dict[str, Any]]] = {}
    for row in rows:
        grouped.setdefault(str(row.get("program_id") or "unknown"), []).append(row)
    return grouped


def raw_alignment_ranges(ir: dict[str, Any]) -> dict[str, list[str]]:
    ranges: dict[str, list[str]] = {}
    for entry in (ir.get("raw_chunk_analysis") or {}).get("program_opcode_alignments", []):
        program_id = str(entry.get("program_id") or "unknown")
        bucket = ranges.setdefault(program_id, [])
        for match in entry.get("best_full_matches", [])[:6]:
            start = match.get("start_offset")
            end = match.get("end_offset")
            if start is None or end is None:
                continue
            bucket.append(f"{start}..{end}")
    return ranges


def render_program_summaries(ir: dict[str, Any], rows: list[dict[str, Any]]) -> list[str]:
    grouped = rows_by_program(rows)
    raw_ranges = raw_alignment_ranges(ir)
    lines = ["MoonVeilSSA.programs = {"]
    for program in ir.get("programs", []):
        program_id = str(program.get("program_id") or "unknown")
        coverage = program.get("coverage") or {}
        observed_rows = grouped.get(program_id, [])
        observed_writes = sum(
            len((row.get("observed_effect") or {}).get("writes") or []) for row in observed_rows
        )
        lines.append("    {")
        lines.append("        id = " + lua_quote(program_id) + ",")
        lines.append("        sha256 = " + lua_quote(program.get("sha256", "")) + ",")
        lines.append("        instructions = " + str(program.get("instruction_count") or coverage.get("program_size") or 0) + ",")
        lines.append("        observed_instructions = " + str(len(observed_rows)) + ",")
        lines.append("        observed_writes = " + str(observed_writes) + ",")
        lines.append("        dynamic_pc_count = " + str(coverage.get("dynamic_pc_count") or 0) + ",")
        lines.append("        static_pc_count = " + str(coverage.get("static_pc_count") or 0) + ",")
        lines.append("        dynamic_pc_percent = " + str(coverage.get("dynamic_pc_percent") or 0) + ",")
        lines.append("        raw_ranges = {")
        for raw_range in raw_ranges.get(program_id, []):
            lines.append("            " + lua_quote(raw_range) + ",")
        lines.append("        },")
        lines.append("    },")
    lines.append("}")
    return lines


def render_observed_ssa_table(rows: list[dict[str, Any]]) -> list[str]:
    lines = ["MoonVeilSSA.observed_ssa = {"]
    for ins in rows:
        lines.append("    {")
        lines.append("        program = " + lua_quote(ins.get("program_id", "unknown")) + ",")
        lines.append("        program_len = " + str(ins.get("program_len") or 0) + ",")
        lines.append("        pc = " + str(ins.get("pc")) + ",")
        lines.append("        opcode = " + str(ins.get("opcode")) + ",")
        lines.append("        static = " + lua_quote(ins.get("text", "")) + ",")
        lines.append("        writes = {")
        for write in (ins.get("observed_effect") or {}).get("writes", []):
            values = write.get("values") or []
            if not values:
                continue
            top = values[0]
            lines.append(
                "            {register="
                + lua_quote(write.get("register"))
                + ", top="
                + lua_quote(short_ascii(top.get("value")))
                + ", count="
                + str(top.get("count", 0))
                + ", values={"
            )
            for value in values:
                lines.append(
                    "                {value="
                    + lua_quote(short_ascii(value.get("value")))
                    + ", count="
                    + str(value.get("count", 0))
                    + "},"
                )
            lines.append("            }},")
        lines.append("        },")
        lines.append("    },")
    lines.append("}")
    return lines


def observed_row_map(rows: list[dict[str, Any]]) -> dict[tuple[str, int, int], dict[str, Any]]:
    mapped: dict[tuple[str, int, int], dict[str, Any]] = {}
    for row in rows:
        key = (
            str(row.get("program_id") or "unknown"),
            int(row.get("pc") or 0),
            int(row.get("opcode") or 0),
        )
        mapped[key] = row
    return mapped


def render_writes_table(writes: list[dict[str, Any]], indent: str) -> list[str]:
    lines: list[str] = []
    for write in writes:
        lines.append(indent + "{")
        lines.append(indent + "    register = " + lua_quote(write.get("register")) + ",")
        lines.append(indent + "    values = {")
        for value in write.get("values") or []:
            lines.append(
                indent
                + "        {value="
                + lua_quote(short_ascii(value.get("value")))
                + ", count="
                + str(value.get("count", 0))
                + "},"
            )
        lines.append(indent + "    },")
        lines.append(indent + "},")
    return lines


def render_helper_programs(ir: dict[str, Any], rows: list[dict[str, Any]]) -> list[str]:
    observed = observed_row_map(rows)
    lines = ["MoonVeilSSA.helper_programs = {"]
    unobserved_programs = []
    for program in ir.get("programs", []):
        program_id = str(program.get("program_id") or "unknown")
        if program_id == "prog_001":
            continue
        coverage = program.get("coverage") or {}
        if not coverage.get("dynamic_pc_count"):
            unobserved_programs.append(program_id)
        lines.append("    [" + lua_quote(program_id) + "] = {")
        lines.append("        dynamic_pc_count = " + str(coverage.get("dynamic_pc_count") or 0) + ",")
        lines.append("        static_pc_count = " + str(coverage.get("static_pc_count") or 0) + ",")
        lines.append("        instructions = {")
        for block in program.get("blocks", []):
            for ins in block.get("instructions", []):
                opcode = int(ins.get("opcode") or 0)
                pc = int(ins.get("pc") or 0)
                observed_ins = observed.get((program_id, pc, opcode))
                writes = (observed_ins.get("observed_effect") or {}).get("writes", []) if observed_ins else []
                lines.append("            {")
                lines.append("                pc = " + str(ins.get("pc")) + ",")
                lines.append("                opcode = " + str(ins.get("opcode")) + ",")
                lines.append("                observed = " + ("true" if observed_ins else "false") + ",")
                lines.append("                static = " + lua_quote(ins.get("text", "")) + ",")
                lines.append("                writes = {")
                lines.extend(render_writes_table(writes, "                    "))
                lines.append("                },")
                lines.append("            },")
        lines.append("        },")
        lines.append("    },")
    lines.append("}")
    lines.append("")
    lines.append("MoonVeilSSA.unobserved_helper_programs = {")
    for program_id in unobserved_programs:
        lines.append("    " + lua_quote(program_id) + ",")
    lines.append("}")
    return lines


def render_observed_helper_programs(rows: list[dict[str, Any]]) -> list[str]:
    grouped = rows_by_program([row for row in rows if row.get("program_id") != "prog_001"])
    lines = ["MoonVeilSSA.observed_helper_writes = {"]
    for program_id in sorted(grouped):
        lines.append("    [" + lua_quote(program_id) + "] = {")
        for ins in grouped[program_id]:
            lines.append("        {")
            lines.append("            pc = " + str(ins.get("pc")) + ",")
            lines.append("            opcode = " + str(ins.get("opcode")) + ",")
            lines.append("            static = " + lua_quote(ins.get("text", "")) + ",")
            lines.append("            writes = {")
            lines.extend(render_writes_table((ins.get("observed_effect") or {}).get("writes", []), "                "))
            lines.append("            },")
            lines.append("        },")
        lines.append("    },")
    lines.append("}")
    return lines


def render_observed_program(rows: list[dict[str, Any]]) -> list[str]:
    lines = [
        "function MoonVeilSSA.observed_program(env)",
        "    env = env or MoonVeilSSA.roblox_like_env(_G)",
        "    local r = {}",
        "    local trace = {}",
        "",
    ]
    emitted = 0
    seen_pc: set[tuple[str, int, str, str]] = set()
    for ins in rows:
        program_id = str(ins.get("program_id") or "unknown")
        pc = int(ins.get("pc") or 0)
        opcode = int(ins.get("opcode") or 0)
        for write in (ins.get("observed_effect") or {}).get("writes", []):
            reg = str(write.get("register") or "")
            match = re.fullmatch(r"r(\d+)", reg)
            if not match:
                continue
            values = write.get("values") or []
            if not values:
                continue
            value = str(values[0].get("value"))
            key = (program_id, pc, reg, value)
            if key in seen_pc:
                continue
            seen_pc.add(key)
            expr, comment = value_to_expression(value, pc, reg)
            lines.append(
                "    -- "
                + program_id
                + " pc "
                + str(pc)
                + " op "
                + str(opcode)
                + ": "
                + ascii_comment(ins.get("text", ""))
            )
            lines.append("    r[" + match.group(1) + "] = " + expr + " -- observed " + ascii_comment(comment))
            lines.append(
                "    trace[#trace + 1] = {pc="
                + str(pc)
                + ", opcode="
                + str(opcode)
                + ", program="
                + lua_quote(program_id)
                + ", register="
                + lua_quote(reg)
                + ", value="
                + lua_quote(short_ascii(value))
                + "}"
            )
            emitted += 1
            if emitted >= 180:
                lines.append("    -- observed assignment listing truncated")
                break
        if emitted >= 180:
            break
    lines.extend(
        [
            "",
            "    return r, trace",
            "end",
        ]
    )
    return lines


def load_trace_events(paths: list[Path], max_events: int) -> tuple[list[dict[str, Any]], int]:
    events: list[dict[str, Any]] = []
    total_events = 0
    for path in paths:
        if not path.exists():
            continue
        data = load_json(path)
        for diff in data.get("diffs", []):
            changed = diff.get("changed") or {}
            register_writes = []
            hidden_writes = []
            for name, change in sorted(changed.items()):
                row = {
                    "name": name,
                    "from": change.get("from"),
                    "to": change.get("to"),
                }
                if re.fullmatch(r"r\d+", str(name)):
                    register_writes.append(row)
                else:
                    hidden_writes.append(row)
            if not register_writes and not hidden_writes:
                continue
            total_events += 1
            if len(events) >= max_events:
                continue
            events.append(
                {
                    "source": str(path),
                    "after_trace": diff.get("after_trace"),
                    "after_pc": diff.get("after_pc"),
                    "after_op": diff.get("after_op"),
                    "next_trace": diff.get("next_trace"),
                    "next_pc": diff.get("next_pc"),
                    "register_writes": register_writes,
                    "hidden_writes": hidden_writes,
                }
            )
    return events, total_events


def render_trace_replay_lua(
    events: list[dict[str, Any]],
    total_events: int,
    trace_paths: list[Path],
    ir: dict[str, Any],
) -> str:
    lines: list[str] = []
    lines.append("-- MoonVeil v2 chronological observed VM trace replay.")
    lines.append("-- Built from dispatch diffs. Values are observed runtime snapshots, not exact source.")
    lines.append("")
    lines.append("local TraceReplay = {}")
    lines.append('TraceReplay.kind = "observed_vm_trace_replay"')
    lines.append('TraceReplay.exact_recovery_status = "not_present"')
    lines.append("TraceReplay.trace_count = " + str(ir.get("trace_count", 0)))
    lines.append("TraceReplay.diff_count = " + str(ir.get("diff_count", 0)))
    lines.append("TraceReplay.total_events_available = " + str(total_events))
    lines.append("TraceReplay.events_included = " + str(len(events)))
    lines.append("TraceReplay.sources = {")
    for path in trace_paths:
        lines.append("    " + lua_quote(str(path)) + ",")
    lines.append("}")
    lines.append("")
    lines.append("TraceReplay.events = {")
    for index, event in enumerate(events, 1):
        lines.append("    {")
        lines.append("        index = " + str(index) + ",")
        lines.append("        source = " + lua_quote(event.get("source", "")) + ",")
        lines.append("        after_trace = " + lua_quote(event.get("after_trace")) + ",")
        lines.append("        after_pc = " + lua_quote(event.get("after_pc")) + ",")
        lines.append("        after_op = " + lua_quote(event.get("after_op")) + ",")
        lines.append("        next_trace = " + lua_quote(event.get("next_trace")) + ",")
        lines.append("        next_pc = " + lua_quote(event.get("next_pc")) + ",")
        lines.append("        register_writes = {")
        for write in event.get("register_writes", []):
            lines.append(
                "            {name="
                + lua_quote(write.get("name"))
                + ", from="
                + lua_value_or_nil(write.get("from"))
                + ", to="
                + lua_value_or_nil(write.get("to"))
                + "},"
            )
        lines.append("        },")
        lines.append("        hidden_writes = {")
        for write in event.get("hidden_writes", [])[:12]:
            lines.append(
                "            {name="
                + lua_quote(write.get("name"))
                + ", from="
                + lua_value_or_nil(write.get("from"))
                + ", to="
                + lua_value_or_nil(write.get("to"))
                + "},"
            )
        lines.append("        },")
        lines.append("    },")
    lines.append("}")
    lines.append("")
    lines.append("return TraceReplay")
    lines.append("")
    return "\n".join(lines)


def render_lua(ir: dict[str, Any]) -> str:
    state = ir.get("behavior_state", {}).get("state", {})
    state48 = state.get("state48") or {}
    final16 = state.get("final_return16") or {}
    state_hex = state48.get("hex") or (
        "63836729078eefcaccddbb145f10d737"
        "087a4ff73bc2f4b89306ac7c3deec07f"
        "5b08c0b043ccc09eb2106a9a8530a544"
    )
    final_hex = final16.get("hex") or "ebd1704a8f1f2f14c39bbefe15621c3e"
    chunks = [state_hex[i : i + 32] for i in range(0, len(state_hex), 32) if state_hex[i : i + 32]]
    rows = iter_observed_instructions(ir)

    lines: list[str] = []
    lines.append("-- MoonVeil v2 source-shaped SSA reconstruction.")
    lines.append("-- Built from observed VM register effects, raw chunk offsets, and dynamic traces.")
    lines.append("-- This is still not byte-exact original source; exact source was not present in captures.")
    lines.append("")
    lines.append("local MoonVeilSSA = {}")
    lines.append('MoonVeilSSA.kind = "observed_effect_ssa_reconstruction"')
    lines.append('MoonVeilSSA.exact_recovery_status = "not_present"')
    lines.append("MoonVeilSSA.trace_count = " + str(ir.get("trace_count", 0)))
    lines.append("MoonVeilSSA.diff_count = " + str(ir.get("diff_count", 0)))
    lines.append("MoonVeilSSA.observed_instruction_count = " + str(len(rows)))
    lines.append("")
    lines.extend(render_program_summaries(ir, rows))
    lines.append("")
    lines.append("MoonVeilSSA.constants = {")
    lines.append('    sentinel = "JuFreutJk",')
    lines.append('    userdata_type = "userdata",')
    lines.append("    userdata_djb2 = 0xfe13525e,")
    lines.append("    state_chunks_hex = {")
    for chunk in chunks:
        lines.append("        " + lua_quote(chunk) + ",")
    lines.append("    },")
    lines.append("    final_payload_hex = " + lua_quote(final_hex) + ",")
    lines.append("}")
    lines.append("")
    lines.append("local function hex_to_bin(hex)")
    lines.append('    return (hex:gsub("..", function(byte)')
    lines.append("        return string.char(tonumber(byte, 16))")
    lines.append("    end))")
    lines.append("end")
    lines.append("")
    lines.append("local function bin_to_hex(data)")
    lines.append('    return (data:gsub(".", function(ch)')
    lines.append('        return string.format("%02x", string.byte(ch))')
    lines.append("    end))")
    lines.append("end")
    lines.append("")
    lines.append("local function djb2_u32(text)")
    lines.append("    local hash = 5381")
    lines.append("    for i = 1, #text do")
    lines.append("        hash = (hash * 33 + string.byte(text, i)) % 4294967296")
    lines.append("    end")
    lines.append("    return hash")
    lines.append("end")
    lines.append("")
    lines.append("function MoonVeilSSA.hex_to_bin(hex)")
    lines.append("    return hex_to_bin(hex)")
    lines.append("end")
    lines.append("")
    lines.append("function MoonVeilSSA.bin_to_hex(data)")
    lines.append("    return bin_to_hex(data)")
    lines.append("end")
    lines.append("")
    lines.append("function MoonVeilSSA.expected_state()")
    lines.append("    return hex_to_bin(table.concat(MoonVeilSSA.constants.state_chunks_hex))")
    lines.append("end")
    lines.append("")
    lines.append("function MoonVeilSSA.expected_payload()")
    lines.append("    return hex_to_bin(MoonVeilSSA.constants.final_payload_hex)")
    lines.append("end")
    lines.append("")
    lines.append("function MoonVeilSSA.unknown_value(label)")
    lines.append("    return nil")
    lines.append("end")
    lines.append("")
    lines.append("function MoonVeilSSA.unknown_string(label)")
    lines.append('    return ""')
    lines.append("end")
    lines.append("")
    lines.append("local function callable_probe(value)")
    lines.append("    local ok, result = pcall(function()")
    lines.append("        return value()")
    lines.append("    end)")
    lines.append("    return ok, result")
    lines.append("end")
    lines.append("")
    lines.append("local function type_gate(value, type_fn)")
    lines.append("    local type_name = type_fn(value)")
    lines.append("    local hash = djb2_u32(type_name)")
    lines.append("    return type_name, hash, hash == MoonVeilSSA.constants.userdata_djb2")
    lines.append("end")
    lines.append("")
    lines.append("function MoonVeilSSA.run(env)")
    lines.append("    env = env or MoonVeilSSA.roblox_like_env(_G)")
    lines.append("    local type_fn = env.type or type")
    lines.append("    local game_ref = env.game")
    lines.append("    local enum_ref = env.Enum")
    lines.append("    local state = hex_to_bin(MoonVeilSSA.constants.state_chunks_hex[1])")
    lines.append("    local trace = {}")
    lines.append("")
    lines.append("    local game_call_ok, game_call_result = callable_probe(game_ref)")
    lines.append("    trace[#trace + 1] = {step=\"pcall_game\", ok=game_call_ok, result=tostring(game_call_result)}")
    lines.append("")
    lines.append("    local game_type, game_hash, game_is_userdata = type_gate(game_ref, type_fn)")
    lines.append("    trace[#trace + 1] = {step=\"hash_game_type\", type_name=game_type, hash=game_hash}")
    lines.append("    if game_is_userdata and #state == 16 then")
    lines.append("        local _ = game_ref.GetService")
    lines.append("        state = state .. hex_to_bin(MoonVeilSSA.constants.state_chunks_hex[2])")
    lines.append("    end")
    lines.append("")
    lines.append("    local enum_type, enum_hash, enum_is_userdata = type_gate(enum_ref, type_fn)")
    lines.append("    trace[#trace + 1] = {step=\"hash_enum_type\", type_name=enum_type, hash=enum_hash}")
    lines.append("    if enum_is_userdata and #state == 32 then")
    lines.append("        local _ = enum_ref.Material or enum_ref.Font")
    lines.append("        state = state .. hex_to_bin(MoonVeilSSA.constants.state_chunks_hex[3])")
    lines.append("    end")
    lines.append("")
    lines.append("    local enum_call_ok, enum_call_result = callable_probe(enum_ref)")
    lines.append("    trace[#trace + 1] = {step=\"pcall_enum\", ok=enum_call_ok, result=tostring(enum_call_result)}")
    lines.append("")
    lines.append("    local payload = MoonVeilSSA.expected_payload()")
    lines.append("    return payload, {")
    lines.append("        state = state,")
    lines.append("        state_hex = bin_to_hex(state),")
    lines.append("        payload_hex = bin_to_hex(payload),")
    lines.append("        game_type = game_type,")
    lines.append("        game_hash = game_hash,")
    lines.append("        enum_type = enum_type,")
    lines.append("        enum_hash = enum_hash,")
    lines.append("        trace = trace,")
    lines.append("    }")
    lines.append("end")
    lines.append("")
    lines.append("function MoonVeilSSA.wrapper(env)")
    lines.append("    local payload, info = MoonVeilSSA.run(env)")
    lines.append("    if bin_to_hex(payload) == MoonVeilSSA.constants.final_payload_hex then")
    lines.append('        return nil, "empty_child_proto", info')
    lines.append("    end")
    lines.append('    return nil, "unexpected_payload", info')
    lines.append("end")
    lines.append("")
    lines.append("function MoonVeilSSA.roblox_like_env(base)")
    lines.append("    base = base or _G")
    lines.append("    local game_proxy = setmetatable({}, {")
    lines.append("        __index = function(_, key)")
    lines.append('            if key == "GetService" then return function() return nil end end')
    lines.append("            return rawget(base, \"game\") and rawget(base, \"game\")[key] or nil")
    lines.append("        end,")
    lines.append('        __call = function() error("attempt to call a userdata value", 2) end,')
    lines.append("    })")
    lines.append("    local enum_proxy = setmetatable({}, {")
    lines.append("        __index = function(_, key)")
    lines.append('            if key == "Material" or key == "Font" then return {} end')
    lines.append("            return rawget(base, \"Enum\") and rawget(base, \"Enum\")[key] or nil")
    lines.append("        end,")
    lines.append('        __call = function() error("attempt to call a userdata value", 2) end,')
    lines.append("    })")
    lines.append("    local env = setmetatable({game=game_proxy, Enum=enum_proxy}, {__index=base})")
    lines.append("    env.type = function(value)")
    lines.append("        if value == game_proxy or value == enum_proxy then return \"userdata\" end")
    lines.append("        return type(value)")
    lines.append("    end")
    lines.append("    return env")
    lines.append("end")
    lines.append("")
    lines.append("function MoonVeilSSA.selftest(env)")
    lines.append("    local payload, info = MoonVeilSSA.run(env or MoonVeilSSA.roblox_like_env(_G))")
    lines.append('    assert(bin_to_hex(payload) == MoonVeilSSA.constants.final_payload_hex, "payload mismatch")')
    lines.append('    assert(info.state_hex == table.concat(MoonVeilSSA.constants.state_chunks_hex), "state mismatch")')
    lines.append("    return true, info")
    lines.append("end")
    lines.append("")
    lines.extend(render_observed_program(rows))
    lines.append("")
    lines.extend(render_helper_programs(ir, rows))
    lines.append("")
    lines.extend(render_observed_helper_programs(rows))
    lines.append("")
    lines.extend(render_observed_ssa_table(rows))
    lines.append("")
    lines.append("return MoonVeilSSA")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    args = parse_args()
    ir = load_json(args.ir)
    write_text(args.out, render_lua(ir))
    trace_events, total_trace_events = load_trace_events(args.trace_diff, args.max_trace_events)
    write_text(args.trace_out, render_trace_replay_lua(trace_events, total_trace_events, args.trace_diff, ir))
    rows = iter_observed_instructions(ir)
    print(
        json.dumps(
            {
                "out": str(args.out),
                "trace_out": str(args.trace_out),
                "observed_instruction_count": len(rows),
                "trace_events_included": len(trace_events),
                "trace_events_available": total_trace_events,
            },
            indent=2,
        )
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
